<?php

namespace Database\Seeders;

use App\Models\RefSchool;
use App\Models\RefSchoolLevel;
use Illuminate\Database\Seeder;

class RefSchoolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        RefSchoolLevel::truncate();

        $date = [
            "05" => [
                "school_level" => "Preschool",
                "school_list" => [
                    "No previous school (Not specified)",
                    "Dumalagan Day Care Center",
                    "Philippine Electronics & Communication Institute of Technology",
                ],
            ],
            "04" => [
                "school_level" => "Grade School",
                "school_list" => [
                    "Happy Kids Multiple Intelligence Preschool Inc.",
                    "Enfant Cheri Study Center Inc.",
                    "Cornerstone Christian Progressive School",
                    "Faith Baptist Christian Academy",
                    "Couples For Christ School of the Morning Star",
                    "Light and Life Learning Center",
                    "Philippine Electronics & Communication Institute of Technology",
                    "Rainbow of Angels Learning Center",
                    "Butuan City Mission Academy",
                    "Holistic Heart Study Center, Inc.",
                    "Libertad Central Elementary School",
                    "Angelicum Montessori School",
                    "Bliss Elementary School",
                    "Butuan Central Elementary School",
                    "Doongan Integrated School",
                    "Obrero Elementary School",
                    "Sacred Heart School of Butuan, Inc.",
                    "Alliance School",
                    "Ampayon Elementary School",
                    "Asian Institute of Computer Studies, Cebu Branch",
                    "Ateneo De Manila",
                    "Baan Elementary School",
                    "Baptist Heritage Learning Center of Ampayon,Inc.",
                    "Butuan City SPED Center",
                    "Cahayagan Elementary School",
                    "CGC Child Center Carrascal",
                    "Cheerful Cherubs Learning Center of Butuan, Inc.",
                    "College of the Immaculate Conception",
                    "Consuelo Elementary School",
                    "Cubi-cubi Elementary School",
                    "Dumalagan Day Care Center",
                    "Father Saturnino Urios University (Returnee)",
                    "Holy Child Colleges of Butuan",
                    "Jose T. Domingo Sr. Central Elementary School",
                    "Kalilid Elementary School",
                    "Kinamlutan Elementary School.",
                    "Maon Elementary School",
                    "Masao Elementary School",
                    "Messiah Baptist Learning Center",
                    "Monroe Elementary School",
                    "Pagadian City Pilot School",
                    "Sacred Heart de Iloilo-Pavia",
                    "Saint Michael College of Caraga",
                    "Schildknecht School",
                    "Solid Rock Shilo Mission Academy, Inc.",
                    "Surigao City Pilot School",
                    "University of San Carlos-SG CEBU",


                ],
            ],
            "03" => [
                "school_level" => "Junior High School",
                "school_list" => [
                    "Rainbow of Angels ",
                    "Morning Star",
                    "Cornerstone",
                    "Butuan Central Elementary School",
                    "Libertad Elem. School",
                    "Enfant Cheri",
                    "Sacred Heart School of Butuan",
                    "Ambago Elementary School",
                    "Ampayon Elementary School",
                    "Butuan City Mission Academy",
                    "Faith Baptist Christian Academy of Butuan",
                    "Saint Joseph Institute of Technology",
                    "Butuan Sped",
                    "La Trinidad Int.",
                    "Doongan Integrated School",
                    "San Vicente National High School",
                    "Briliant Star Christian Academy",
                    "St. Joseph Academy Dasmarinas Inc.",
                    "Cantisay Elementary School",
                    "Nasipit Central Elementary School",
                    "Pinamanculan Elem, School",
                    "Buenavista SPED",
                    "Light and Life Learning Center",
                    "Cabcabon Elementary School",
                    "San Rafael Elem, School",
                    "Ateneo De Davao",
                    "Maon Integrated School",
                    "Mandacpan Elem. School",
                    "Buenavista National High School",
                    "Loreto Central Elementary School",
                    "Amazing Grace Agape Mission Academy Inc.",
                ],
            ],
            "02" => [
                "school_level" => "Senior High School",
                "school_list" => [
                    "Alegria National High School",
                    "Agusan National High School",
                    "Alviola Village ISS",
                    "Ambago Integrated",
                    "Ampayon National High School",
                    "Angelicum Montessori",
                    "Bayugan National Comprehensive High School",
                    "Buenavista National High School",
                    "Buenavista SPED High School",
                    "Butuan Central Elementary School",
                    "Butuan City School of Arts and Trades",
                    "Butuan City School of Arts and Trades",
                    "Cabadbaran Baptist Academy",
                    "Cabadbaran National High School",
                    "Candelaria Institute",
                    "Cantilan National High School",
                    "Caraga Regional Science High School",
                    "Caraga State University",
                    "Christ the King College",
                    "CITCI",
                    "CKAT",
                    "Consuelo National High School",
                    "De La Salle",
                    "Enfant Cheri",
                    "Father Urios Institute Technology Ampayon",
                    "General Luna National High School",
                    "Good Shepherd Christian Academy",
                    "Hinatuan National High School",
                    "Holistic Heart Study Center Inc.",
                    "Immaculate Heart Mary Academy",
                    "Jabonga National High School",
                    "Kitcharao national High School",
                    "La Soledad NHS",
                    "Las Nieves NationalHigh School",
                    "Libertad National High School",
                    "Loreto National High School",
                    "Lumbocan National High School",
                    "Morning Star",
                    "Mount Carmel College",
                    "Nasipit Central School",
                    "Nasipit Vocational School",
                    "Nicaan High School",
                    "Northern Mindanao Colleges",
                    "Panagangan National High School",
                    "Philippine Electronics and Communication",
                    "Philippine Science High School",
                    "Rainbow",
                    "Saint James High School",
                    "Saint Joseph Institute Technology",
                    "Saint Michael College Caraga",
                    "Saint Theresa College Tandag",
                    "Saint-Louis College",
                    "San Luis National High School",
                    "San Vicente National High School",
                    "St. Isidor",
                    "Talacogon National High School",
                    "Timber City Academy",
                    "Tubod National High School",
                    "Tungao National High School",
                    "West Integrated School",
                ],
            ],
            "01" => [
                "school_level" => "College",
                "school_list" => [
                    "Agusan National High School",
                    "Butuan City School Of Arts and Trades",
                    "Libertad National High School",
                    "Bayugan National Comprehensive High School",
                    "Father Saturnino Urios University Pueblos",
                    "Saint James High School",
                    "Timber City Academy",
                    "Saint Joseph Institute Technology",
                    "San Vicente National High School",
                    "Father Urios Institute of Technology - Ampayon",
                    "Candelaria Institute of Technology",
                    "Taligaman National High School",
                    "Northern Mindanao Colleges",
                    "Cabadbaran City National High School",
                    "CFC School of the Morning Star",
                    "Father Saturnino Urios University Morelos",
                    "Northeastern Mindanao Academy",
                    "San Luis National High School",
                    "Agusan Pequeno National High School",
                    "Magallanes National High School",
                    "Saint Michael College of Caraga",
                    "Agusan Colleges, Inc.",
                    "Amparo National High School",
                    "Lumbocan National High School",
                    "Banza National High School",
                    "Butuan Christian Community School",
                    "Father Saturnino Urios College Bayugan",
                    "Immaculate Heart of Mary Academy",
                    "Buenavista Special Education High School",
                    "Agay National High School",
                    "Agusan del Sur National Science High School",
                    "Agusan del Sur National High School",
                    "Angelicum Montessori School",
                    "Buenavista National High School",
                    "Enfant Cheri Study Centre, Inc.",
                    "Esperanza National High Scool",
                    "Las Nieves National High School",
                    "Tungao National High School",
                    "Alviola Village Integrated Secondary School",
                    "Ampayon National High School",
                    "Pigdaulan National High School",
                    "Pigdaulan National High School",
                    "Caraga State University Cabadbaran Campus",
                    "Father Saturnino Urios College of Sibagat Incorporated",
                    "Santiago National High School",
                    "Mahay integrated secondary school",
                    "Mindanao Institute",
                    "Nasipit National Vocational School",
                    "Fr. Urios Academy of Magallanes, Inc.",
                    "Jagupit National High School",
                    "Agusan Del Sur College, Inc.",
                    "Alegria National High School",
                    "Florida National High School",
                    "Pagatpatan National High School",
                    "Panagangan Lapaz Agusan Del sur",
                    "Pinamanculan National High School",
                    "St. Paul University Surigao",
                    "Surigao del Norte National High School",
                    "Tagbina National High School",
                    "Holy Child Academy of Marihatag Inc.",
                    "Diatagon Catholic High School",
                    "Kinamlutan National High School",
                    "Mother of Mercy Academy",
                    "Cabcabon National High School",
                    "Sibagat National High School",
                    "Agusan Sur National High School",
                    "Sibagat National High School of Home Industries",
                    "Talacogon National High School",
                    "Sto. Nino National High School",
                    "Mount Carmel College",
                    "Anticala National High School",
                    "Butuan Central Elementary School",
                    "Calamba National High School",
                    "Carmen National High School",
                    "Claver National High School",
                    "De La Salle John Bosco College",
                    "Good Shepherd Christian Academy",
                    "Guinabsan National High School",
                    "Holy Child Colleges of Butuan",
                    "La Paz National High School",
                    "Pedro D. Duncano National High School",
                    "Philippine Electronics and Communication Institute of Technology",
                    "Rizal National High School",
                    "Sacred Heart School of Butuan",
                    "San Roque Parish High School",
                    "Northwestern Agusan Colleges",
                    "Zillovia National High School",
                    "Unidad National High School",
                    "Taganito National High School",
                    "Agusan Institute Of Technology",
                    "Amando A. Fabio Memorial National High School",
                    "Alternative Learning System",
                    "Aupagan National High School",
                    "Barobo National High School",
                    "Bunawan National High School",
                    "Butuan City Colleges",
                    "Christ the King College",
                    "Consuelo National High School",
                    "Daniel R. Aguinaldo National High School",
                    "Dapa National High School",
                    "De La Salle John Bosco College",
                    "Del Monte National High School",
                    "Father Saturnino College Of Sibagat Inc.",
                    "Florita Herrera Irizari National High School",
                    "Father Urios Academy Of Magallanes Inc",
                    "Gigaquit National High School",
                    "Jacinto P Elpa National High School",
                    "Kalamansig National High School",
                    "Kibungsod National High School",
                    "La Trinidad Integrated Secondary School",
                    "Lapinigan National High School",
                    "Loreto National High School",
                    "Los angeles national high school",
                    "Mindanao State University Saguiaran Community High School",
                    "New Northern Mindanao Colleges Incorporated",
                    "Our Lady Of Carmen Academy Of Caraga, Incorporated",
                    "Saint Ignatius Loyola Academy Inc..",
                    "Saint Michael College Cantilan Incorporated",
                    "Saint Vincent de Paul Diocesan College",
                    "San Toribio National High School",
                    "Siargao National Science High School",
                    "Sisters of Mary School Girlstown Inc,.",
                    "Sta. Irene National High School",
                    "Sta. Lucia High School",
                    "St. Mary's Academy of Carmen",
                    "Surigao City National High School",
                    "Tabon M. Estrella National High School",
                    "Adamson University",
                    "Addition Hills Integrated School",
                    "Amontay Community Learning Center",
                    "Anakan National High School",
                    "Anex Village National High School",
                    "Anislagan National High School",
                    "Assumption Academy of Compostela",
                    "Angeles City National High School",
                    "Bagbaguin National High School",
                    "Balang Balang National High School",
                    "Ballesteros National HighSchool",
                    "Banagher College",
                    "Basag national high school",
                    "Bislig City National High School",
                    "Butuan City Comprehensive High School",
                    "Cabadbaran City Baptist Academy (CBA) INC.",
                    "Cabantian National High school",
                    "Cahayagan National High School",
                    "Calaitan Bayugan City",
                    "Bohol Wisdom School",
                    "Bonifacio Aquino Elementary School",
                    "Camaya-an National High School",
                    "Candabong nation high school",
                    "Cantapoy National High School",
                    "Caraga Regional Science High School",
                    "Carrascal National High School",
                    "Cavite Bible Baptist Academy",
                    "Datu Lipus Makapandong National High School",
                    "Dilangalen National High School",
                    "Don Jose Memorial College",
                    "Don Ruben Edera Ecleo Sr. Memorial National High School",
                    "Dona Rosario National High School",
                    "E. G. Montilla National High School",
                    "F. Bangoy National High School",
                    "F.S Omayana National High School",
                    "Father Saturnino Urios College Of Trento,Inc.",
                    "FS Omayana National High School",
                    "Garcia Elementary School",
                    "General Luna National High School",
                    "Gingoog City Colleges",
                    "Gingoog City Comprehensive National High School",
                    "Guadalupe National High School",
                    "Agusan Del Sur National Science High School",
                    "Harvest Christian School International",
                    "Hawilian National High School",
                    "Hinaplanon National High School",
                    "Hinatuan National Comprehensive High School",
                    "Holy Child School Of Antipolo",
                    "Holy Nazarene Christian School",
                    "Immaculate Concepcion Academy",
                    "Jabonga National High School",
                    "Juan Sumulong High School",
                    "Kalingagan National High School",
                    "Kidapawan City National High School",
                    "Kitcharao National High School",
                    "Laboratory High School- Normisist Campus",
                    "Lagro High School",
                    "Lianga National Comprehensive High School",
                    "Libas Sud Integrated School",
                    "Lingayao National High School",
                    "Lonoy Heroes Memorial High School",
                    "Loong National High School",
                    "Lucena National High School",
                    "Madrid National High School",
                    "Magaud National High School",
                    "Magpayang National High School",
                    "Maguinda National High School",
                    "Maibu National High School",
                    "Major Inocencio B. Mendez High Shool",
                    "Malingin National High School",
                    "Manapa National High School",
                    "Mandacpan Elementary School",
                    "Mangagoy National High School",
                    "Maningalao National High School",
                    "Mantangale National High School",
                    "Maria Clara Lorenzo Lobregat National High School",
                    "Masao Elementary School",
                    "Mesaieed International School",
                    "Mindanao Mission Academy",
                    "Misamis Occidental National High School",
                    "Misamis Oriental General Comprehensive High School",
                    "Molave Vocational Technical School",
                    "Monkayo National High School",
                    "Mount Carmel High School",
                    "Mt. Olive National High School",
                    "Noli National High School",
                    "Norcaces Integrated School",
                    "Notre Dame Of Misayap Of College",
                    "Our Lady Of Fatima Academy",
                    "Our Lady Of Lourdes College",
                    "Pacifican Institute Of Agusan",
                    "Padiay National High School",
                    "Pareja Integrated Secondary School",
                    "Pasay City West High School",
                    "Philippine Science High School - Caraga Region Campus",
                    "Pintuyan National High School",
                    "Pres. Diosdado Macapagal High School",
                    "Prosperidad National High School",
                    "Rainbow Speech World Learning Center Inc",
                    "Remedios T. Romualdez Central Elementary School",
                    "Riverside Integrated Secondary School",
                    "Saint Augustine High School",
                    "Saint Theresa College of Tandag, Inc.",
                    "Salvacion National High School",
                    "San Antonio School",
                    "San Isidro National High School",
                    "San Jose National High School",
                    "San Nicholas Academy",
                    "San Nicolas School",
                    "Sangay National High School",
                    "Sapao National High School",
                    "Sering National High School",
                    "Signal Village National High School",
                    "Simbalan National High School",
                    "Saint Joseph Institute of Technology - Annex",
                    "Smnchs San Roque Annex",
                    "Southern Technological Institute Of The Philippines",
                    "Sta. Cruz National High School",
                    "St. Christine National High School",
                    "St. Mary's Academy Of Talisayan",
                    "St. Michael's School Of Madrid, Inc.",
                    "Sto.Tomas National High School",
                    "Sumile National High School",
                    "Surigao City Pilot School",
                    "Surigao Education Center",
                    "Surigao Sur Colleges",
                    "Toledo S. Pantilo Sr. Memorial National High School",
                    "Trento National High School",
                    "Tubay Central Elementary",
                    "Tubod National High School",
                    "Tugbok National High School",
                    "Tumanan National High School",
                    "Urios College Of Trento",
                    "Urios High School",
                    "Valencia National High School",
                    "Victory Christian International School",
                    "Vinapor National High School",
                    "Wakat National High School",
                    "West Prosperidad National High School",
                    "Xavier Academy",
                    "Taft National High School",
                    "Talisay National High School",
                    "Tagkiling Tribal Integrated Secondary School",
                    "Tandag National Science High School",
                    "Timamana National High School",

                ],
            ],

        ];

        foreach ($date as $key => $value) {
            $schoolLevel = RefSchoolLevel::create([
                "school_level" => $value['school_level'],
                "created_by" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ]);

            foreach ($value['school_list'] as $key2 => $value2) {
                $dataSchool = [
                    "school_level_id" => $schoolLevel->id,
                    "school_name" => $value2,
                    "status" => "Active",
                    "created_by" => 1,
                    "created_at" => now(),
                    "updated_at" => now(),
                ];

                RefSchool::create($dataSchool);
            }
        }
    }
}
